export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR';

export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR';

export const FETCH_COVID_HISTORY = 'FETCH_COVID_HISTORY';
export const FETCH_COVID_HISTORY_REQUEST = 'FETCH_COVID_HISTORY_REQUEST';
export const FETCH_COVID_HISTORY_SUCCESS = 'FETCH_COVID_HISTORY_SUCCESS';
export const FETCH_COVID_HISTORY_ERROR = 'FETCH_COVID_HISTORY_ERROR';
